### ISSUE TITLE
insepeckage软件使用问题

### ISSUE THREAD

**Issue by a1023182899** [locoz666/spider-article#2]
问题（insepeckage软件使用）

1，adb logcat > C:\Users\swt\Desktop\log.txt
会导出很多无用的运行日志，adb如何只导出hash，也就是加密的那些数据

2，我在127.0.0.1:8008这个网页中的扳手（setting），只将hash开启，但是其他数据却还是出现，为什么？

**Comment by locoz666** [comment]
1、adb logcat可以过滤内容，用grep之类的工具即可，或者在Android Studio中操作，可以直接写正则表达式过滤出所有Hash开头的日志。
2、没有试过这么用，可能是作者还没实现这个功能？

**Comment by locoz666** [comment]
@a1023182899
